version: '3.8'
services:
  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: vibewave
  web:
    build: .
    container_name: web
    ports:
      - "9090:8080"
    environment:
      DB_HOSTNAME: db
      DB_PORT: 5432
      GOOGLE_APPLICATION_CREDENTIALS: /app/google-credentials.json
      MAIL_PSWD: wmmndxqpodrdafzx
